openapi: 3.0.1
info:
    title: Tuleap farm management
    description: 'Tuleap farm management API '
    version: 1.0.0
servers:
    - url: https://localhost/rest.php/tuleap
tags:
    - name: instance
      description: Instance management
    - name: maintenance
      description: Maintanence functions
paths:
    /instance/_list:
        get:
            tags:
                - instance
            summary: Get list of available instances
            operationId: listInstances
            responses:
                200:
                    description: Success
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/InstanceList'
            security:
                - farm-management-auth: []
    /instance/{name}:
        get:
            tags:
                - instance
            summary: Get status of the instance
            operationId: getIntanceStatus
            parameters:
                - name: name
                  in: path
                  description: Instance name
                  required: true
                  schema:
                      type: string
            responses:
                200:
                    description: Success
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/InstanceStatus'
                404:
                    description: Name valid, but instance does not exist
                    content: {}
                422:
                    description: Invalid input
                    content: {}
            security:
                - farm-management-auth: []
        put:
            tags:
                - instance
            summary: Create new instance
            description: Body params which are not specified will default to "master" instance
                configs
            operationId: createInstance
            parameters:
                - name: name
                  in: path
                  description: Instance name
                  required: true
                  schema:
                      type: string
            requestBody:
                description: Initial configuration
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/CreateConfiguration'
                required: true
            responses:
                200:
                    description: Create instance process started
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ProcessResponse'
                422:
                    description: Invalid instance name
                    content: {}
            security:
                - farm-management-auth: []
            x-codegen-request-body-name: body
        delete:
            tags:
                - instance
            summary: Delete instance
            operationId: deleteInstance
            parameters:
                - name: name
                  in: path
                  description: Instance name
                  required: true
                  schema:
                      type: string
            responses:
                200:
                    description: Delete instance process started
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ProcessResponse'
                404:
                    description: Instance not found
                    content: {}
            security:
                - farm-management-auth: []
    /instance/rename/{name}/{newname}:
        post:
            tags:
                - instance
            summary: Renames existing instance
            operationId: renameInstance
            parameters:
                - name: name
                  in: path
                  description: Instance name
                  required: true
                  schema:
                      type: string
                - name: newname
                  in: path
                  description: New instance name
                  required: true
                  schema:
                      type: string
            responses:
                200:
                    description: Instance rename process started
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ProcessResponse'
                404:
                    description: Instance not found
                    content: {}
                422:
                    description: Invalid instance name
                    content: {}
            security:
                - farm-management-auth: []
    /instance/suspend/{name}:
        post:
            tags:
                - instance
            summary: Suspend instance
            operationId: suspendInstance
            parameters:
                - name: name
                  in: path
                  description: Instance name
                  required: true
                  schema:
                      type: string
            responses:
                200:
                    description: Instance suspended
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/SuccessResponse'
                404:
                    description: Instance not found
                    content: {}
                422:
                    description: Invalid instance name
                    content: {}
            security:
                - farm-management-auth: []
    /instance/resume/{name}:
        post:
            tags:
                - instance
            summary: Resume instance
            operationId: resumeInstanace
            parameters:
                - name: name
                  in: path
                  description: Instance name
                  required: true
                  schema:
                      type: string
            responses:
                200:
                    description: Instance resumed
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/SuccessResponse'
                404:
                    description: Instance not found
                    content: {}
                422:
                    description: Invalid instance name
                    content: {}
            security:
                - farm-management-auth: []
    /maintenance/{instance}/{script}:
        post:
            tags:
                - maintenance
            summary: Executes a maintenance script on the instance or all instances
            operationId: maintenanceOp
            parameters:
                - name: instance
                  in: path
                  description: Instance name on which to run the script. If specified instance
                      name is "*", script will be executed on all instances
                  required: true
                  schema:
                      type: string
                - name: script
                  in: path
                  description: Script key to execute
                  required: true
                  schema:
                      type: string
                      enum:
                          - runjobs
                          - update
                          - refresh-links
                          - set-user-groups
                          - terminate-sessions
            requestBody:
                description: Params to be passed to the script as input (example for set-user-groups)
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/MaintenanceSample'
                required: false
            responses:
                200:
                    description: successful operation
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ProcessResponse'
                400:
                    description: Instance not found or not ready (not avialable for running
                        a script)
                    content: {}
                422:
                    description: Invalid instance name
                    content: {}
            x-codegen-request-body-name: body
            security:
                - farm-management-auth: []
components:
    schemas:
        CreateConfiguration:
            required:
                - adminpass
                - project_id
            type: object
            properties:
                dbserver:
                    type: string
                dbuser:
                    type: string
                dbpass:
                    type: string
                adminuser:
                    type: string
                project_id:
                    type: integer
                adminpass:
                    type: string
                lang:
                    type: string
                extra:
                    type: array
                    items:
                        type: string
                        example: any arbitrary data to be available on instance calls
        ProcessResponse:
            type: object
            properties:
                status:
                    type: string
                    example: "finished"
                output:
                    type: string
                    example: "some output data"
        InstanceStatus:
            type: object
            properties:
                status:
                    type: string
                    enum:
                        - ready
                        - maintenance
                        - initializing
        SuccessResponse:
            type: object
            properties:
                success:
                    type: boolean
                    example: true
        InstanceList:
            type: array
            items:
                type: string
                example: Instance A
        MaintenanceSample:
            type: object
            properties:
                groups:
                    type: object
                    properties:
                        WikiSysop:
                            type: array
                            items:
                                type: string
                                example: sysop
        ProcessStatus:
            type: object
            properties:
                pid:
                    type: string
                started_at:
                    type: string
                    example: "20220209125814"
                status:
                    type: string
                    enum:
                        - finished
                        - running
                        - error
                output:
                    type: object
                    properties: {}
                    description: Whatever the process returned as output
    securitySchemes:
        farm-management-auth:
            type: oauth2
            flows:
                clientCredentials:
                    tokenUrl: http://localost/rest.php/oauth2/access_token
                    scopes: {}
